// Autogenerated from Pigeon (v16.0.5), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: public_member_api_docs, non_constant_identifier_names, avoid_as, unused_import, unnecessary_parenthesis, prefer_null_aware_operators, omit_local_variable_types, unused_shown_name, unnecessary_import, no_leading_underscores_for_local_identifiers

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List, Uint8List;

import 'package:flutter/foundation.dart' show ReadBuffer, WriteBuffer;
import 'package:flutter/services.dart';

PlatformException _createConnectionError(String channelName) {
  return PlatformException(
    code: 'channel-error',
    message: 'Unable to establish connection on channel: "$channelName".',
  );
}

class FileMessage {
  FileMessage({
    required this.text,
    required this.content,
  });

  String text;

  String content;

  Object encode() {
    return <Object?>[
      text,
      content,
    ];
  }

  static FileMessage decode(Object result) {
    result as List<Object?>;
    return FileMessage(
      text: result[0]! as String,
      content: result[1]! as String,
    );
  }
}

class Response {
  Response({
    required this.successful,
    this.error,
  });

  bool successful;

  String? error;

  Object encode() {
    return <Object?>[
      successful,
      error,
    ];
  }

  static Response decode(Object result) {
    result as List<Object?>;
    return Response(
      successful: result[0]! as bool,
      error: result[1] as String?,
    );
  }
}

class _DeviceFileApiCodec extends StandardMessageCodec {
  const _DeviceFileApiCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is FileMessage) {
      buffer.putUint8(128);
      writeValue(buffer, value.encode());
    } else if (value is Response) {
      buffer.putUint8(129);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 128: 
        return FileMessage.decode(readValue(buffer)!);
      case 129: 
        return Response.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

class DeviceFileApi {
  /// Constructor for [DeviceFileApi].  The [binaryMessenger] named argument is
  /// available for dependency injection.  If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  DeviceFileApi({BinaryMessenger? binaryMessenger})
      : __pigeon_binaryMessenger = binaryMessenger;
  final BinaryMessenger? __pigeon_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _DeviceFileApiCodec();

  Future<Response> saveFile(FileMessage msg) async {
    const String __pigeon_channelName = 'dev.flutter.pigeon.save_content_as_txt_file.DeviceFileApi.saveFile';
    final BasicMessageChannel<Object?> __pigeon_channel = BasicMessageChannel<Object?>(
      __pigeon_channelName,
      pigeonChannelCodec,
      binaryMessenger: __pigeon_binaryMessenger,
    );
    final List<Object?>? __pigeon_replyList =
        await __pigeon_channel.send(<Object?>[msg]) as List<Object?>?;
    if (__pigeon_replyList == null) {
      throw _createConnectionError(__pigeon_channelName);
    } else if (__pigeon_replyList.length > 1) {
      throw PlatformException(
        code: __pigeon_replyList[0]! as String,
        message: __pigeon_replyList[1] as String?,
        details: __pigeon_replyList[2],
      );
    } else if (__pigeon_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (__pigeon_replyList[0] as Response?)!;
    }
  }
}
